services:
  db:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: atimera
      POSTGRES_PASSWORD: atilaenzo
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  atiservices:
    container_name: atiservices-api
    image: atimera/atiservices-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dbatiservices
    ports:
      - "8088:8080"
    networks:
      - db
    restart: unless-stopped
    depends_on:
      - db
#  Au lieu d'une commande, on utilise une variable d'env : SPRING_DATASOURCE_URL
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/dbatiservices

networks:
  db:
    driver: bridge

volumes:
  postgres:
  pgadmin: