name: CI - Build Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ 'main', 'releases/**' ]
    paths:
      - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-latest
     # Service containers to run with `container-job`

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16.1
        # Provide the password for postgres
        env:
          POSTGRES_USER: atimera
          POSTGRES_PASSWORD: atilaenzo
          POSTGRES_DB: dbatiservices
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5332:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests and Create/Deploy image to docker hub
        run: mvn -B -nts verify jib:build --file pom.xml
